# Generated by Django 3.0.6 on 2020-06-27 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200626_0921'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='userProfile',
            new_name='Profile',
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.customUser'),
        ),
    ]
